name:                French
version:             0.1.0.0
github:              "githubuser/French"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/French#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.0
- Chart >= 1.9
- Chart-cairo >= 1.9
- colour >= 2.3
- containers >= 0.5
- data-default >= 0.7
- hashable >= 1.2
- hmatrix >= 0.20
- hmatrix-gsl-stats >= 0.4.1
- hmatrix-nlopt
- loch-th >= 0.2.2
- normaldistribution >= 1.1
- parallel >= 3.2.2
- random >= 1.2
- random-shuffle >= 0.0.4
- split >= 0.2.3
- statistics >= 0.15
- text >= 0.1
- text >= 1.0
- time >= 1.4
- unordered-containers >= 0.2.5
- vector >= 0.10

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - FlexibleInstances
    - OverloadedStrings
    - TypeSynonymInstances

executables:
  French-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - French

tests:
  French-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - French
