* French

A Haskell library for backtesting portfolios built using the Ken French Data Library and other data sources.

** TODO Installation

https://docs.haskellstack.org/en/stable/

*** Installing the code
This is a Haskell project that uses the Stack package manager. For instructions on installing Stack, see the official website: https://docs.haskellstack.org/en/stable/

To run French, open terminal and navigate to French's root directory.

To compile:

=stack build=

To run:

=stack exec French-exe=

Or use the =make= command to compile and run French in a single step. =make= suppresses some compiler messaging, so if you run into trouble, run =stack build= to diagnose the problem.
*** Downloading the data
I have a pre-packaged collection of formatted data from the [[https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html][Ken French Data Library]], [[https://www.aqr.com/Insights/Datasets/][AQR's Datasets]], and other sources, available on Google Drive: https://drive.google.com/file/d/1mArqxgPZohDim__hk7azuyFRk0BEpE8j/view?usp=sharing

Download that .zip file and unpack it in this project's root directory. You should see a =resources/= directory, which is the directory that French will read data from.

There is a Bash script located at =scripts/update-all-french.sh= that automatically re-downloads most Ken French files to keep them up to date. It only re-downloads files that are already present in the =resources/French/= directory, so you can't use it for a first-time download.
** TODO Usage

To explain:

- [ ] loading data; getting returns for a strategy; printing summary stats
- [ ] advanced functions (longShortTrend, factor regressions, etc.)
- [ ] scripts
- [ ] replication code: use `stack runghc filename.hs`

** TODO Examples

Print US equity returns using the Fama-French 3 Factors data:

TODO write required imports

#+BEGIN_SRC haskell
import French

main = do
  -- Load the contents of resources/French/3_Factors.csv into a `QuoteMap`
  quotes <- loadDB "French/3_Factors.csv"

  let riskFreeRate :: RetSeries
      riskFreeRate = getRets1 "RF" quotes

      -- Ken French Data Library stores market returns as excess of risk-free
      -- rate, not absolute returns. We'll have to add the risk-free rate back
      -- in.
      mktMinusRF = getRets1 "Mkt-RF" quotes

      -- The `RetSeries` type is treated as a number, so it's possible to do
      -- arithmetic on return series. The `(+)` operator adds the returns of
      -- each period.
      mkt = mktMinusRF + riskFreeRate

  putStrLn "=== US Equity Stats ==="
  printStats mkt
#+END_SRC

Create a line graph of US equity prices (continuing the previous example):

#+BEGIN_SRC haskell
  -- Narrow `mkt` to a single decade.
  let singleDecade = startingPeriod 2000 1 $ endingPeriod 2009 12 mkt

  -- This is a quick way to narrow `rfDecade` to include only the dates from
  -- `singleDecade`. When two `RetSeries` are added, the result includes only
  -- dates that occur in both operands.
  let rfDecade = riskFreeRate + 0 * singleDecade

  let mktPrices = returnsToPrices singleDecade
  let rfPrices = returnsToPrices rfDecade

  plotLineGraph "output.png"
    "US Equities 2000–2009"  -- title
    "Price"                  -- y-axis label
    [ ("Equities", mktPrices)
    , ("T-bills", rfPrices)
    ]
#+END_SRC

Run a factor regression:

#+BEGIN_SRC haskell
  myPortfolio <- retsFromFile1 "French/Portfolios_B-M_Value_Wt.csv" "Hi 20"
  let smb = getRets1 "SMB" quotes
  let hml = getRets1 "HML" quotes

  printFactorRegression myPortfolio rf [mkt - rf, smb, hml] ["Mkt", "SMB", "HML"]
#+END_SRC

Because src_haskell{RetSeries} is a numeric type, the compiler can treat numeric literals as src_haskell{RetSeries}. For example, if you want to set the risk-free rate to zero, you can do it like this:

#+BEGIN_SRC haskell
  shortSide <- retsFromFile1 "French/Portfolios_B-M_Value_Wt.csv" "Hi 30"
  let myNewFactor = myPortfolio - shortSide

  -- myNewFactor is market-neutral, so we want to set rf to 0 in the regression
  printFactorRegression myNewFactor 0 [mkt - rf, smb, hml] ["Mkt", "SMB", "HML"]
#+END_SRC
